// Generated by CoffeeScript 1.9.2
(function() {
  var buildDbSecurityObject, config, expect;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  config = require('../config');

  buildDbSecurityObject = require('../buildDbSecurityObject');

  describe("a security object", function() {
    return it("should be made for a specific db", function(done) {
      var secu;
      secu = config.database.securityObject;
      secu = buildDbSecurityObject(secu, "testDb");
      secu.admins.names.length.must.be(1);
      secu.admins.names[0].must.be("admin");
      secu.admins.roles.length.must.be(1);
      secu.admins.roles[0].must.be("testDb/admin");
      secu.members.names.length.must.be(0);
      secu.members.roles.length.must.be(2);
      secu.members.roles.must.contain("testDb/beekeeper");
      secu.members.roles.must.contain("testDb/uploader");
      return done();
    });
  });

}).call(this);
