// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, config, createViews, dbDriver, expect, promisify_db;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  config = require('../config');

  promisify_db = require('../../../openbeelab-db-util/javascript/promisify_dbDriver');

  dbDriver = require('../../../openbeelab-db-util/javascript/dbDriver');

  Promise = require('promise');

  createViews = require('../create_views');

  describe("create views for the config db", function() {
    var configDb, dbServer, instance;
    instance = null;
    dbServer = null;
    configDb = null;
    before(function(done) {
      instance = require('../../../mock-couch').createServer();
      instance.listen(config.database.port);
      dbServer = dbDriver.connectToServer(config.database);
      configDb = dbServer.useDb(config.database.name + "_config");
      return configDb.create().then(function() {
        return done();
      })["catch"](function(err) {
        console.log(err);
        return done(err);
      });
    });
    after(function(done) {
      instance.close();
      return done();
    });
    return it("should create all expected views", function(done) {
      return createViews(configDb, "config").then(function() {
        return configDb.save({
          _id: "test_stand",
          type: 'stand',
          name: 'a test stand'
        });
      }).then(function() {
        return configDb.save({
          _id: 'test_location',
          type: 'location',
          name: 'a test location'
        });
      }).then(function() {
        return configDb.get('_design/stands/_view/all');
      }).then(function(data) {
        expect(data).to.not.be.falsy();
        data.total_rows.must.be(1);
        return done();
      })["catch"](function(err) {
        return done(err);
      });
    });
  });

  describe("create views for the data db", function() {
    var dataDb, dbServer, instance;
    instance = null;
    dbServer = null;
    dataDb = null;
    before(function(done) {
      instance = require('../../../mock-couch').createServer();
      instance.listen(config.database.port);
      dbServer = dbDriver.connectToServer(config.database);
      dataDb = dbServer.useDb(config.database.name + "_data");
      return dataDb.create().then(function() {
        dataDb.save({
          _id: "test_measure",
          type: 'measure',
          name: 'a test measure',
          value: 53.6
        });
        return done();
      })["catch"](function(err) {
        console.log(err);
        return done(err);
      });
    });
    after(function(done) {
      instance.close();
      return done();
    });
    return it("should create all expected views", function(done) {
      return createViews(dataDb, "data").then(function() {
        return dataDb.get('_design/measures/_view/all');
      }).then(function(data) {
        data.total_rows.must.be.at.least(1);
        return done();
      })["catch"](function(err) {
        return done(err);
      });
    });
  });

}).call(this);
