// Generated by CoffeeScript 1.10.0
(function() {
  var db, dbConfig, dbDriver, getWeekNumber, measuresUrl;

  dbDriver = require('../../openbeelab-db-util/javascript/dbDriver');

  dbConfig = require('./config');

  db = dbDriver.connectToServer(dbConfig.database).useDb(dbConfig.database.name);

  getWeekNumber = require('../../util/javascript/dateUtil').getWeekNumber;

  measuresUrl = "_design/measures/_view/by_date?startkey=\"2014-12-29T05:15:00.000Z\"&limit=1";

  db.get(measuresUrl, function(err, rows) {
    var i, len, measure, results, row;
    results = [];
    for (i = 0, len = rows.length; i < len; i++) {
      row = rows[i];
      measure = row.value;
      results.push(console.log(getWeekNumber(new Date(measure.timestamp))));
    }
    return results;
  });

}).call(this);
