// Generated by CoffeeScript 1.9.2
(function() {
  var apiary, db, dbConfig, dbDriver, measuresUrl;

  dbDriver = require('../../openbeelab-db-util/javascript/dbUtil');

  dbConfig = require('./config');

  db = dbDriver.database(dbConfig.database);

  measuresUrl = "_design/measures/_view/all";

  apiary = null;

  db.get(measuresUrl, function(err, rows) {
    var i, len, measure, results, row;
    results = [];
    for (i = 0, len = rows.length; i < len; i++) {
      row = rows[i];
      measure = row.value;
      if (measure.beehouse_id) {
        results.push(db.get(measure.beehouse_id, function(err, beehouse) {
          var bh;
          bh = {
            _id: beehouse._id,
            name: beehouse.name
          };
          measure.beehouse = bh;
          delete measure.beehouse_id;
          return db.save(measure);
        }));
      } else {
        results.push(void 0);
      }
    }
    return results;
  });

}).call(this);
