// Generated by CoffeeScript 1.9.2
(function() {
  var db, dbConfig, dbDriver;

  require('yamljs');

  dbDriver = require('../../db/javascript/dbDriver');

  dbConfig = require('../../config.yaml');

  db = dbDriver.connectToServer(dbConfig.database).useDb(dbConfig.database.name);

  db.get('_design/measures/_view/incorrect?', (function(_this) {
    return function(err, measures) {
      var i, len, measure, results;
      results = [];
      for (i = 0, len = measures.length; i < len; i++) {
        measure = measures[i];
        measure = measure.value;
        measure.incorrect_timestamp = measure.timestamp;
        measure.timestamp = new Date();
        measure.fixed = true;
        results.push(db.save(measure));
      }
      return results;
    };
  })(this));

}).call(this);
