// Generated by CoffeeScript 1.10.0
(function() {
  var configCfg, configDb, dataCfg, dataDb, dbConfig, dbDriver, objectUtils;

  objectUtils = require('../../openbeelab-util/javascript/objectUtils');

  objectUtils.install();

  dbDriver = require('../../openbeelab-db-util/javascript/dbDriver');

  dbConfig = require('./config');

  dataCfg = dbConfig.database.clone();

  console.log(dataCfg.name);

  dataDb = dbDriver.connectToServer(dbConfig.database).useDb(dbConfig.database.name);

  configCfg = dbConfig.database.clone();

  configCfg.name += "_config";

  configDb = dbDriver.useDb(configCfg);

  dataDb.get('_all_docs?startkey=\"_design/\"&endkey=\"_design0\"&include_docs=true').then(function(data) {
    var i, len, results, row, rows;
    console.log(data);
    rows = data.rows;
    results = [];
    for (i = 0, len = rows.length; i < len; i++) {
      row = rows[i];
      results.push(console.log(row._id));
    }
    return results;
  });

}).call(this);
