// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(secu, dbName) {
    var i, j, k, len, len1, ref, ref1, role;
    ref = secu.admins.roles;
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      role = ref[i];
      secu.admins.roles[i] = dbName + "/" + role;
    }
    ref1 = secu.members.roles;
    for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
      role = ref1[i];
      secu.members.roles[i] = dbName + "/" + role;
    }
    return secu;
  };

}).call(this);
