// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(config, dbServer) {
    var Promise, createUsers, createViews, dbName, fn, insert_beehouse, insert_location, insert_stand, j, len, ref, user, usersDb, usersPromises, util;
    insert_location = require('./insert_location');
    insert_stand = require('./insert_stand');
    insert_beehouse = require('./insert_beehouse');
    createViews = require('./create_views');
    createUsers = require('./create_users');
    Promise = require("promise");
    util = require('util');
    dbName = config.database.name;
    usersDb = dbServer.useDb("_users");
    usersPromises = [];
    ref = config.database.users;
    fn = function(user) {
      var i, k, len1, ref1, role, userPromise;
      ref1 = user.roles;
      for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
        role = ref1[i];
        user.roles[i] = dbName + "/" + role;
      }
      userPromise = usersDb.save(user);
      userPromise.then(function(res) {
        return user;
      });
      return usersPromises.push(userPromise);
    };
    for (j = 0, len = ref.length; j < len; j++) {
      user = ref[j];
      fn(user);
    }
    return Promise.all(usersPromises).then(function() {
      return console.log("users created.");
    });
  };

}).call(this);
