// Generated by CoffeeScript 1.9.2
(function() {
  var createView, db, dbConfig, viewPath;

  dbConfig = require('./config');

  db = require('../../dbUtil/javascript/dbUtil').database(dbConfig.databases.local);

  createView = require('../../dbUtil/javascript/create_view');

  viewPath = "../../dbUtil/javascript/views/" + process.argv[2];

  createView(db, viewPath, function(err, res) {
    console.log(err);
    return console.log(res);
  });

}).call(this);
