// Generated by CoffeeScript 1.10.0
(function() {
  var db, dbConfig, view;

  dbConfig = require('./config');

  db = require('../../openbeelab-db-util/javascript/dbDriver').connectToServer(dbConfig.database).useDb(dbConfig.database.name);

  view = require("./" + process.argv[2]);

  db.save(view);

}).call(this);
