// Generated by CoffeeScript 1.10.0
(function() {
  var Promise;

  require('../../openbeelab-util/javascript/stringUtils').install();

  Promise = require('promise');

  module.exports = function(usersDb, dbName) {
    var adminPromise, all, dbAdmin, dbUploader, uploaderPromise;
    dbAdmin = {
      _id: 'org.couchdb.user:' + dbName + '_admin',
      type: "user",
      name: dbName + '_admin',
      roles: [dbName + '/admin'],
      password: String.generateToken(6)
    };
    adminPromise = usersDb.save(dbAdmin);
    dbUploader = {
      _id: 'org.couchdb.user:' + dbName + '_uploader',
      type: "user",
      name: dbName + '_uploader',
      roles: [dbName + '/uploader'],
      password: String.generateToken(6)
    };
    uploaderPromise = usersDb.save(dbUploader);
    all = Promise.all([adminPromise, uploaderPromise]);
    return all.then(function() {
      return {
        admin: dbAdmin,
        uploader: dbUploader
      };
    });
  };

}).call(this);
