// Generated by CoffeeScript 1.9.2
(function() {
  var db, dbConfig, view;

  dbConfig = require('./config');

  db = require('../../openbeelab-db-util/javascript/dbDriver').connectToServer(dbConfig.database).useDb(dbConfig.database.name);

  view = require("./" + process.argv[2]);

  console.log(view);

  db.save(view).then(function(res) {
    return console.log(res);
  });

}).call(this);
