// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(db, location, name) {
    var apiary;
    apiary = {
      _id: "apiary:" + name,
      name: name,
      type: "apiary"
    };
    apiary.location_id = location != null ? location._id : void 0;
    return db.save(apiary).then(function() {
      return [db, apiary];
    });
  };

}).call(this);
