// Generated by CoffeeScript 1.10.0
(function() {
  var bunyan;

  bunyan = require('bunyan');

  module.exports = function(name) {
    return bunyan.createLogger({
      name: name,
      level: 'debug'
    });
  };

}).call(this);
