// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/refs',
    views: {
      apiary: {
        map: (function(doc) {
          if (doc.apiary_id != null) {
            return emit(doc.apiary_id, doc);
          }
        }).toString()
      }
    }
  };

}).call(this);
