// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    _id: '_design/auth',
    views: {},
    validate_doc_update: (function(newDoc, oldDoc, userCtx) {
      var isAdmin, isCreation, isDeletion, isLogged, isMember, isUpdate, isUploader;
      isLogged = (userCtx.name != null) && userCtx.name !== '';
      if (!isLogged) {
        throw {
          'forbidden': 'please log in.'
        };
      }
      isDeletion = oldDoc.deleted || oldDoc._deleted;
      isCreation = oldDoc === null;
      isUpdate = !(creation || deletion);
      isAdmin = userCtx.roles.some(function(dbAndRole) {
        var db, ref, role;
        ref = dbAndRole.split("/"), db = ref[0], role = ref[1];
        return db === userCtx.db && role === "admin";
      });
      isMember = userCtx.roles.some(function(dbAndRole) {
        var _, db, ref;
        ref = dbAndRole.split("/"), db = ref[0], _ = ref[1];
        return db === userCtx.db;
      });
      isUploader = userCtx.roles.some(function(dbAndRole) {
        var db, ref, role;
        ref = dbAndRole.split("/"), db = ref[0], role = ref[1];
        return db === userCtx.db && role === 'uploader';
      });
      if (isAdmin) {
        return;
      }
      if (isUploader && isCreation && newDoc.type === "measure") {
        return;
      }
      throw {
        'forbidden': 'not enough rights'
      };
    }).toString()
  };

}).call(this);
