// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/beehouse_monitoring',
    views: {
      new_relative_data: {
        map: (function(doc) {
          if (doc.type === "measure" && doc.absolute_ref !== void 0 && doc.absolute_ref === null) {
            return emit(doc.beehouse_id, doc);
          }
        }).toString()
      },
      absolute_weight: {
        map: (function(doc) {
          if (doc.type === "measure" && doc.name === 'global-weight') {
            return emit([doc.beehouse_id, doc.timestamp], doc);
          }
        }).toString()
      }
    }
  };

}).call(this);
