// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/measures',
    views: {
      all: {
        map: (function(doc) {
          if (doc.type === "measure") {
            return emit(doc._id, doc);
          }
        }).toString()
      },
      by_date: {
        map: (function(doc) {
          if (doc.type === "measure") {
            return emit(doc.timestamp, doc);
          }
        }).toString()
      },
      by_location: {
        map: (function(doc) {
          if (doc.type === "measure" && (doc.location_id != null)) {
            return emit(doc.location_id, doc);
          }
        }).toString()
      },
      by_beehouse: {
        map: (function(doc) {
          if (doc.type === "measure" && (doc.beehouse_id != null)) {
            return emit(doc.beehouse_id, doc);
          }
        }).toString()
      },
      by_location_date_name: {
        map: (function(doc) {
          if (doc.type === "measure" && (doc.location_id != null)) {
            return emit([doc.location_id, doc.timestamp, doc.name], doc);
          }
        }).toString()
      },
      by_location_date_beehouse: {
        map: (function(doc) {
          if (doc.type === "measure" && (doc.location_id != null) && (doc.beehouse_id != null)) {
            return emit([doc.location_id, doc.timestamp, doc.beehouse_id], doc);
          }
        }).toString()
      },
      by_location_date_beehouse_name: {
        map: (function(doc) {
          if (doc.type === "measure" && (doc.location_id != null) && (doc.beehouse_id != null)) {
            return emit([doc.location_id, doc.timestamp, doc.beehouse_id, doc.name], doc);
          }
        }).toString()
      }
    }
  };

}).call(this);
