// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/auth',
    views: {},
    validate_doc_update: (function(newDoc, oldDoc, userCtx) {
      var isLogged;
      isLogged = (userCtx.name != null) && userCtx.name !== '';
      if (!isLogged) {
        throw {
          'forbidden': 'please log in.'
        };
      }
    }).toString()
  };

}).call(this);
