// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/auth',
    views: {},
    validate_doc_update: (function(newDoc, oldDoc, userCtx) {
      var creation, deletion, isAdmin, isLogged, isMember, isUploader, update;
      isLogged = (userCtx.name != null) && userCtx.name !== '';
      if (!isLogged) {
        throw {
          'forbidden': 'please log in.'
        };
      }
      deletion = oldDoc.deleted || oldDoc._deleted;
      creation = oldDoc === null;
      update = !(creation || deletion);
      isAdmin = userCtx.roles.some(function(dbAndRole) {
        var db, ref, role;
        ref = dbAndRole.split("/"), db = ref[0], role = ref[1];
        return db === userCtx.db(role === "admin");
      });
      isMember = userCtx.roles.some(function(dbAndRole) {
        var _, db, ref;
        ref = dbAndRole.split("/"), db = ref[0], _ = ref[1];
        return db === userCtx.db;
      });
      isUploader = userCtx.roles.some(function(dbAndRole) {
        var _, db, ref;
        ref = dbAndRole.split("/"), db = ref[0], _ = ref[1];
        return db === userCtx.db;
      });
      if (!Admin) {
        throw {
          'forbidden': "you're not a member."
        };
      }
    }).toString()
  };

}).call(this);
