// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    _id: '_design/stands',
    views: {
      all: {
        map: (function(doc) {
          if (doc.type === "stand") {
            return emit(doc._id, doc);
          }
        }).toString()
      },
      by_beehouse: {
        map: (function(doc) {
          if (doc.type === "stand" && (doc.beehouse_id != null)) {
            return emit(doc.beehouse_id, doc);
          }
        }).toString()
      },
      by_location: {
        map: (function(doc) {
          if (doc.type === "stand" && (doc.location_id != null)) {
            return emit(doc.location_id, doc);
          }
        }).toString()
      }
    }
  };

}).call(this);
